#! /bin/sh
### BEGIN INIT INFO
# Provides:          tcollector
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts tcollector
### END INIT INFO

TCOLLECTOR_HOME=$(dirname $(readlink -f $0))
PATH=/sbin:/bin:/usr/sbin:/usr/bin
TCOLLECTOR=${TCOLLECTOR_HOME}/tcollector

if [ -r ${TCOLLECTOR_HOME}/tcollector.conf ]; then
    . ${TCOLLECTOR_HOME}/tcollector.conf
fi

PIDFILE=${PIDFILE-"/var/run/tcollector.pid"}
LOGFILE=${LOGFILE-"/var/log/tcollector.log"}
HOSTNAME=${HOSTNAME-$(hostname)}

fix_perms() {
    local file=$1
    if [ ! -f "$file" ]; then
        touch "$file"
    fi
    chown $RUN_AS_USER "$file"
}

case $1 in
    start)
        find "$TCOLLECTOR_HOME" -name '*.pyc' -delete

        START_CMD="$TCOLLECTOR start -H $ATSD_HOST -p $ATSD_PORT\
            -t host=$HOSTNAME -P $PIDFILE --logfile $LOGFILE"

        if [ -n "$RUN_AS_USER" ]; then
            fix_perms $LOGFILE
            fix_perms $PIDFILE
            su -c "$START_CMD" $RUN_AS_USER
        else
            $START_CMD
        fi
        ;;

    stop)
        $TCOLLECTOR stop
        ;;
    restart|force-reload)
        $0 stop && $0 start
        ;;

    status)
        $TCOLLECTOR status
        exit $?
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 2
        ;;
esac